spring.datasource.url=jdbc:postgresql://localhost/alura_series1
spring.datasource.username=postgres
spring.datasource.password=senha0785
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
